name: build
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - '!.github/workflows/Build.yml'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - '!.github/workflows/Build.yml'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17'
        check-latest: true

    - name: Install Tesseract-OCR(windows)
      if: matrix.os == 'windows-latest'
      run: choco install tesseract-ocr

    - name: Install Tesseract-OCR(ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libtesseract-dev -y

    - name: Dep
      run: |
        make dep

    - name: Build
      run: |
        make build
