name: build
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - '!.github/workflows/Build.yml'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - '!.github/workflows/Build.yml'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17'
        check-latest: true

    - name: Dep
      run: |
        sudo apt update
        sudo apt install libtesseract-dev -y
        make dep

    - name: Build
      run: |
        make build
