name: build
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.**'
    - 'email-template.json'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.**'
    - 'email-template.json'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set GoVersion
      run: |
        echo "GoVersion=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oEm 1 '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> ${GITHUB_ENV}
    
    - name: Check out code
      uses: actions/checkout@v2.3.4
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GoVersion }}
      
    - name: Dep
      run: make dep
      
    - name: Build
      run: |
        make build TARGET=linux
        make build TARGET=windows